name: Deploy Chat Application

on:
  push:
    branches:
      - main  # or whatever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace API Key in HTML
      run: |
        # Replace placeholder with the GitHub secret API key
        sed -i 's|{{GROQ_API_KEY}}|${{ secrets.GROQ_API_KEY }}|g' index.html

    - name: Deploy to GitHub Pages (or any hosting)
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
